# Generated by Django 5.2 on 2025-07-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='descriptipon',
            new_name='description',
        ),
    ]
